name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_test:
    uses: ./.github/workflows/test.yml
    with:
      ufbx-rust-ref: ${{ github.ref }}
  ci_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: taiki-e/install-action@v2
        with:
          tool: grcov
      - name: Setup llvm-tools-preview
        run: rustup component add llvm-tools-preview
      - name: Generate source with nightly support
        run: python3 bindgen/generate_rust.py --nightly
      - name: Generate coverage
        run: bash misc/test_coverage.sh
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/coverage.lcov
          verbose: true

