name: CI

on:
  push:
    branches: [ master, integration ]
  pull_request:
    branches: [ master, integration ]

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_test:
    uses: actions/test@main
