name: Test

on:
  workflow_call:
    inputs:
      ufbx-rust-ref:
        required: true
        type: string
      ufbx-ref:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ufbx/ufbx-rust
          ref: ${{ inputs.ufbx-rust-ref }}
          fetch-depth: 2
      - name: Update ufbx
        if: inputs.ufbx-ref
        run: python3 sfs.py --verbose update ufbx=${{ inputs.ufbx-ref }} --overwrite
      - name: Parse ufbx
        run: |
          python3 bindgen/ufbx_parser.py -i ufbx/ufbx.h
          python3 bindgen/ufbx_ir.py
      - name: Generate source
        run: python3 bindgen/generate_rust.py
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
